[project]
name = "the-night-before"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
the-night-before = "tlc.the_night_before:main"